spring:

  profiles:
    active: local

  application:
    name: office

  mvc: { throw-exception-if-no-handler-found: true }
  web:
    resources:
      add-mappings: false

  messages:
    basename: errors

  servlet:
    multipart:
      maxFileSize: 30MB # ?? ??? ?? ??
      maxRequestSize: 30MB

  datasource:
    url: jdbc:mariadb://localhost:3306/dbOjtProject
    username: root
    password: jhlee

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    root: info